-- Insert data into Categoria table
INSERT INTO CATEGORIA (ID_CATEGORIA, NOMBRE) VALUES (1, 'Ficcion');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOMBRE) VALUES (2, 'No Ficcion');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOMBRE) VALUES (3, 'Ciencia');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOMBRE) VALUES (4, 'Historia');

-- Insert data into Libro table
INSERT INTO LIBRO (ID_LIBRO, isbn, AUTOR, ESTADO, TITULO, ID_CATEGORIA) VALUES (1, '9780451524935', 'George Orwell', 'Disponible', '1984', 1);
INSERT INTO LIBRO (ID_LIBRO, isbn, AUTOR, ESTADO, TITULO, ID_CATEGORIA) VALUES (2, '9780062316097', 'Yuval Noah Harari', 'Disponible', 'Sapiens', 2);
INSERT INTO LIBRO (ID_LIBRO, isbn, AUTOR, ESTADO, TITULO, ID_CATEGORIA) VALUES (3, '9780553380163', 'Stephen Hawking', 'Prestado', 'Breve historia del tiempo', 3);
INSERT INTO LIBRO (ID_LIBRO, isbn, AUTOR, ESTADO, TITULO, ID_CATEGORIA) VALUES (4, '9781509827695', 'Charles Darwin', 'Disponible', 'El origen de las especies', 3);
INSERT INTO LIBRO (ID_LIBRO, isbn, AUTOR, ESTADO, TITULO, ID_CATEGORIA) VALUES 
(5, '9780142437230', 'Herman Melville', 'Prestado', 'Moby Dick', 1),               -- Ficción
(6, '9780307474278', 'Malcolm Gladwell', 'Prestado', 'Outliers', 2),              -- No Ficción
(7, '9780345803481', 'Stephen King', 'Prestado', '11/22/63', 1),                  -- Ficción
(8, '9780143127741', 'Bill Bryson', 'Prestado', 'Una breve historia de casi todo', 3); -- Ciencia

-- Insert data into Usuario table
INSERT INTO USUARIO (ID_USUARIO, DIRECCION, NOMBRE, TELEFONO, EMAIL, CONTRASENA) VALUES (1, 'Calle Falsa 123', 'Juan Perez', '555-1234', 'a@prueba.com', '1234');
INSERT INTO USUARIO (ID_USUARIO, DIRECCION, NOMBRE, TELEFONO, EMAIL, CONTRASENA) VALUES (2, 'Avenida Siempre Viva 742', 'Maria Gomez', '555-5678', 'b@prueba.com', '1234');
INSERT INTO USUARIO (ID_USUARIO, DIRECCION, NOMBRE, TELEFONO, EMAIL, CONTRASENA) VALUES (3, 'Boulevard de los Sueños Rotos 456', 'Carlos Sanchez', '555-8765', 'c@prueba.com', '1234');

-- Insert data into RESERVA table
INSERT INTO RESERVA (ID_RESERVA, ESTADO, FECHA_RESERVA, ID_LIBRO, ID_USUARIO) VALUES (1, 'Activa', '2023-10-01', 1, 1);
INSERT INTO RESERVA (ID_RESERVA, ESTADO, FECHA_RESERVA, ID_LIBRO, ID_USUARIO) VALUES (2, 'Cancelada', '2023-10-02', 2, 2);
INSERT INTO RESERVA (ID_RESERVA, ESTADO, FECHA_RESERVA, ID_LIBRO, ID_USUARIO) VALUES (3, 'Activa', '2023-10-03', 3, 3);

-- Insert data into PRESTAMO table
INSERT INTO PRESTAMO (ID_PRESTAMO, ESTADO, FECHA_DEVOLUCION, FECHA_PRESTAMO, ID_LIBRO, ID_USUARIO) VALUES (1, 'Devuelto', '2023-09-15', '2023-09-01', 1, 1);
INSERT INTO PRESTAMO (ID_PRESTAMO, ESTADO, FECHA_DEVOLUCION, FECHA_PRESTAMO, ID_LIBRO, ID_USUARIO) VALUES (2, 'Devuelto', '2023-09-20', '2023-09-05', 2, 2);
INSERT INTO PRESTAMO (ID_PRESTAMO, ESTADO, FECHA_DEVOLUCION, FECHA_PRESTAMO, ID_LIBRO, ID_USUARIO) VALUES (3, 'Activo', '2023-09-25', '2023-09-10', 3, 3);
INSERT INTO PRESTAMO (ID_PRESTAMO, ESTADO, FECHA_DEVOLUCION, FECHA_PRESTAMO, ID_LIBRO, ID_USUARIO)
VALUES
(4, 'Activo', CURRENT_DATE + INTERVAL '1' DAY, CURRENT_DATE - INTERVAL '5' DAY, 5, 1),
(5, 'Activo', CURRENT_DATE + INTERVAL '2' DAY, CURRENT_DATE - INTERVAL '4' DAY, 6, 1),
(6, 'Activo', CURRENT_DATE + INTERVAL '3' DAY, CURRENT_DATE - INTERVAL '3' DAY, 7, 1),
(7, 'Activo', CURRENT_DATE + INTERVAL '4' DAY, CURRENT_DATE - INTERVAL '2' DAY, 8, 1);
